steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'backend-service',
    '--image', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA',
    '--region', 'us-central1', # Sesuaikan region sesuai kebutuhan
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]
substitutions:
  _SERVICE_NAME: 'backend-service'
  _REGION: 'us-central1'
timeout: 1200s
